---
version: '3.5'
services:

  producer-repro-107760:
    build:
      context: ../../reproduction-models/connect-connect-filestream-sink/producer-repro-107760/
    hostname: producer
    container_name: producer-repro-107760
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
      TOPIC: "a-topic"
      REPLICATION_FACTOR: 1
      NUMBER_OF_PARTITIONS: 1
      NB_MESSAGES: 1 # -1 for MAX_VALUE
      MESSAGE_BACKOFF: 1000 # Frequency of message injection
      KAFKA_ACKS: "all" # default: "1"
      KAFKA_REQUEST_TIMEOUT_MS: 20000
      KAFKA_RETRY_BACKOFF_MS: 500
      KAFKA_CLIENT_ID: "my-java-producer-repro-107760"
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      JAVA_OPTS: 
    volumes:
      - ../../environment/plaintext/jmx-exporter:/usr/share/jmx_exporter/

  client-kafkajs:
    build:
      context: ../../reproduction-models/connect-connect-filestream-sink/client-kafkajs-107760/
    hostname: client-kafkajs
    container_name: client-kafkajs

  kafkacat:
    image: confluentinc/cp-kafkacat
    hostname: kafkacat
    container_name: kafkacat
    depends_on:
      - broker
    command: "bash -c 'sleep infinity'"

  connect:
    environment:
      # in newer version, it is located in /usr/share/filestream-connectors
      CONNECT_PLUGIN_PATH: /usr/share/java/,/usr/share/confluent-hub-components/,/usr/share/filestream-connectors