---
version: '3.5'
services:
  connect:
    volumes:
        - ../../connect/connect-gcp-gcs-sink/keyfile.json:/tmp/keyfile.json:ro
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-gcs

  kafkacat:
    image: confluentinc/cp-kafkacat
    hostname: kafkacat
    container_name: kafkacat
    depends_on:
      - broker
    command: "bash -c 'sleep infinity'"