---
version: '3.5'
services:
  oracle:    
    image: wnameless/oracle-xe-11g-r2
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../../connect/connect-cdc-oracle11-source/ora-setup-scripts/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ../../connect/connect-cdc-oracle11-source/ora-setup-scripts/02_init.sql:/docker-entrypoint-initdb.d/02_init.sql
      - ../../reproduction-models/connect-connect-cdc-oracle11-source/ora-startup-scripts-105303/01_create_customers.sh:/docker-entrypoint-initdb.d/03_create_customers.sh
      - ../../reproduction-models/connect-connect-cdc-oracle11-source/ora-startup-scripts-105303/02_populate_customer.sh:/docker-entrypoint-initdb.d/04_populate_customer.sh
    environment:
      ORACLE_ALLOW_REMOTE: "true"

  connect:
    build:
      context: ../../reproduction-models/connect-connect-cdc-oracle11-source/repro-105303/
      args:
        CONNECT_TAG: ${CONNECT_TAG}
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - oracle
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-oracle-cdc
      # CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      # CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      # https://github.com/vdesabou/kafka-docker-playground/issues/1461
      # On CP 5.x ORA-01882: timezone region not found
      KAFKA_OPTS: -Duser.timezone=GMT
                  -Doracle.jdbc.timezoneAsRegion=false
