---
version: '3.5'
services:
  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/jcustenborder-kafka-connect-spooldir,/usr/share/confluent-hub-components/jcustenborder-kafka-connect-transform-common