---
version: '3.5'
services:
  oracle:
    # You need to build this image first, following the instructions at
    # https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md
    image: ${ORACLE_IMAGE}
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../../ccloud/fully-managed-connect-cdc-oracle19-source/ora-setup-scripts-cdb-table:/opt/oracle/scripts/setup
      - ../../ccloud/fully-managed-connect-cdc-oracle19-source/ora-startup-scripts-cdb-table:/opt/oracle/scripts/startup
    environment:
      ORACLE_PWD: Admin123

  # https://github.com/shkoliar/docker-ngrok
  ngrok:
    image: shkoliar/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4551:4551
    links:
      - oracle
    environment:
      DOMAIN: oracle
      PORT: 1521
      PROTOCOL: tcp
      REGION: eu
      AUTH_TOKEN: $NGROK_AUTH_TOKEN
      DEBUG: "true"