---
version: '3.5'
services:
  connect:
    volumes:
      - $HOME/.aws/$AWS_CREDENTIALS_FILE_NAME:$CONNECT_CONTAINER_HOME_DIR/.aws/credentials
      - $HOME/.aws/config:$CONNECT_CONTAINER_HOME_DIR/.aws/config
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-s3
      CONNECT_CONSUMER_CLIENT_ID: connect-topic-backup
      CONNECT_CONSUMER_GROUP_ID: connect-topic-backup

      CONNECT_PRODUCER_CLIENT_ID: connect-topic-backup
      CONNECT_PRODUCER_GROUP_ID: connect-topic-backup

      CONNECT_CLIENT_ID: connect-topic-backup
      CONNECT_GROUP_ID: connect-topic-backup