---
version: '3.5'
services:

  postgres:
    image: debezium/postgres:10
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    volumes:
     - ../../ccloud/fully-managed-connect-debezium-postgresql-source/customers.sql:/docker-entrypoint-initdb.d/z99_dump.sql

  ngrok:
    image: shkoliar/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4551:4551
    links:
      - postgres
    environment:
      DOMAIN: postgres
      PORT: 5432
      PROTOCOL: tcp
      REGION: eu
      AUTH_TOKEN: $NGROK_AUTH_TOKEN
      DEBUG: "true"