---
version: '3.5'
services:

  jms-sender:
    build:
      context: ../../reproduction-models/connect-connect-jms-weblogic-source/jms-sender/
    hostname: jms-sender
    container_name: jms-sender
    volumes:
        - ../../connect/connect-jms-weblogic-source/jms-sender/lib/wlthint3client.jar:/tmp/wlthint3client.jar
        - ../../connect/connect-jms-weblogic-source/jms-sender/lib/weblogic.jar:/tmp/weblogic.jar
        
  weblogic-jms:
    image: weblogic-jms:latest
    hostname: weblogic-jms
    container_name: weblogic-jms
    ports:
      - '7001:7001'

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - weblogic-jms
    volumes:
        - ../../connect/connect-jms-weblogic-source/jms-sender/lib/wlthint3client.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms/lib/wlthint3client.jar
        - ../../reproduction-models/connect-connect-jms-weblogic-source/JsonFieldToHeader/target/JsonFieldToHeader-1.0.0-SNAPSHOT-jar-with-dependencies.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms/lib/JsonFieldToHeader-1.0.0-SNAPSHOT-jar-with-dependencies.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jms
      # CONNECT_LOG4J_ROOT_LOGLEVEL: TRACE
