---
version: '3.5'
services:
  connect:
    ports:
      - "5439:5439"
    volumes:
      - $HOME/.aws/$AWS_CREDENTIALS_FILE_NAME:$CONNECT_CONTAINER_HOME_DIR/.aws/credentials
      - $HOME/.aws/config:$CONNECT_CONTAINER_HOME_DIR/.aws/config
      - ../../ccloud/connect-aws-redshift-sink/RedshiftJDBC4-1.2.20.1043.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-aws-redshift/lib/RedshiftJDBC4-1.2.20.1043.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-aws-redshift
      # CONNECT_CONFLUENT_TOPIC: "my_license_topic"
      CONNECT_CONFLUENT_LICENSE: "your license here"
      CONNECT_CONFLUENT_TOPIC_BOOTSTRAP_SERVERS: "$BOOTSTRAP_SERVERS"
      CONNECT_CONFLUENT_TOPIC_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: "3"
      CONNECT_CONFLUENT_TOPIC_SASL_MECHANISM: "PLAIN"
      CONNECT_CONFLUENT_TOPIC_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG