---
version: '3.5'
services:
  simple-send:
    build:
      context: ../../ccloud/fully-managed-connect-azure-event-hubs-source/simple-send/
      args:
        TAG: ${TAG}
        CP_BASE_IMAGE: ${CP_BASE_IMAGE}
        KAFKA_CLIENT_TAG: ${KAFKA_CLIENT_TAG}
    hostname: simple-send
    container_name: simple-send